name: Build

on:
  push:
    branches:
      - 'master' #запускать при пуше в мастер

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: maven_package #название шага
        id: mvn # ид шага
        continue-on-error: true
        run: mvn -B clean package #билд с тестами
      - name: deploy_app
        if: ${{steps.mvn.outcome == 'success'}} #если предыдущий шаг успшный, запустить деплой
        id: deploy
        continue-on-error: true
        uses: appleboy/ssh-action@v0.1.10
        env:
          APP: "CicdApplication" #имя процесса == имя класса с Main
          REPO: "cicd" #папка с репозиторием
        with:
          host: ovz2.j06255807.no4lp.vps.myjino.ru
          username: root
          key: ${{secrets.KEY}}
          port: 49232
          password: 44rl1996
          envs: APP, REPO #какие переменные использовать
          script: cd $REPO && git pull origin master && export APP=$APP && bash start-script.sh
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: -933719856 # id чата
          token: 6259651648:AAHxT-1sYfWIcRQD-Bo6moYgu9gJZ7AJIYo # токен бота
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
              
            Repository: ${{ github.repository }}
            
            Jobs results:
            - maven_package: ${{steps.mvn.outcome}}
            - deploy_app: ${{steps.deploy.outcome}} 
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}