name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: maven_package
        id: mvn
        continue-on-error: true
        run: mvn -B clean package
      - name: deploy_app
        if: ${{steps.mvn.outcome == 'success'}}
        id: deploy
        continue-on-error: true
        uses: appleboy/ssh-action@v0.1.10
        env:
          APP: "CicdApplication"
        with:
          host: ovz2.j06255807.no4lp.vps.myjino.ru
          username: root
          key: ${{secrets.KEY}}
          port: 49232
          password: 44rl1996
          envs: APP
          script: cd cicd && git pull origin master && export APP=$APP && bash start-script.sh
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: -933719856
          token: 6259651648:AAHxT-1sYfWIcRQD-Bo6moYgu9gJZ7AJIYo
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
              
            Repository: ${{ github.repository }}
            
            Jobs results:
            - maven_package: upper(${{steps.mvn.outcome}})
            - deploy_app: ${{steps.deploy.outcome}})
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}