name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: Maven Package
        run: mvn -B clean package -DskipTests