name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: Maven Package
        run: mvn -B clean package
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.KEY }}
#          port: ${{ secrets.PORT }}
#          script: echo $APP
        with:
          host: ovz2.j06255807.no4lp.vps.myjino.ru
          username: root
          key: '@4rl1996'
          port: 49232
          script: echo $APP